import {
  AnatomicalSystem,
  PatientCase,
  PipelineStageInfo,
  PLABQuestion,
  StudentMasteryProfile,
} from "./types";

export const ANATOMICAL_SYSTEMS: AnatomicalSystem[] = [
  {
    id: "cardiovascular",
    name: "Cardiovascular System",
    description: "Coronary circulation, cardiac chambers, conduction pathways, and great vessels.",
    clinicalFocus: "Acute Coronary Syndromes (STEMI vs NSTEMI), Tamponade, Aortic Dissection",
    hotspots: [
      {
        id: "lad_artery",
        name: "Left Anterior Descending (LAD) Artery",
        position: [0.3, 0.4, 0.9],
        clinicalSignificance: "Supplies anterior 2/3 of interventricular septum & anterior left ventricular wall. Known as the 'Widow Maker'.",
        relatedCondition: "Anterolateral Myocardial Infarction (ST elevation in V1-V4)",
        recommendedTutorQuery: "Explain management of acute anterior STEMI involving LAD occlusion according to NICE NG185.",
        highYieldMcqId: "mcq_stemi_01",
        niceGuidelineRef: "NICE-NG185:Section 1.2",
      },
      {
        id: "aortic_root",
        name: "Ascending Aorta & Root",
        position: [-0.1, 1.1, 0.4],
        clinicalSignificance: "Receives high systolic shear stress from left ventricular ejection. Prone to Stanford Type A dissection.",
        relatedCondition: "Acute Stanford Type A Aortic Dissection with pulse deficit & diastolic murmur",
        recommendedTutorQuery: "What is the immediate pharmacological blood pressure target and surgical indication in acute aortic dissection?",
        highYieldMcqId: "mcq_dissection_01",
        niceGuidelineRef: "NICE-CG95:Section 2.4",
      },
      {
        id: "mitral_valve",
        name: "Mitral Valve Complex",
        position: [0.5, -0.2, 0.5],
        clinicalSignificance: "Papillary muscle rupture (often posteromedial after RCA occlusion) causes acute severe mitral regurgitation and cardiogenic shock.",
        relatedCondition: "Post-infarction Acute Mitral Regurgitation & Pulmonary Edema",
        recommendedTutorQuery: "Differentiate acute papillary muscle rupture from ventricular septal rupture post-MI.",
        highYieldMcqId: "mcq_mitral_01",
        niceGuidelineRef: "NICE-NG185:Section 1.5",
      },
    ],
  },
  {
    id: "neurological",
    name: "Central Nervous System",
    description: "Cerebral vascular territories, Circle of Willis, and brainstem nuclei.",
    clinicalFocus: "Ischaemic Stroke, Subarachnoid Hemorrhage, Middle Cerebral Artery territory",
    hotspots: [
      {
        id: "mca_territory",
        name: "Middle Cerebral Artery (M1 Segment)",
        position: [0.7, 0.5, 0.4],
        clinicalSignificance: "Supplies lateral cerebral hemisphere. Occlusion causes contralateral hemiplegia and hemisensory loss (face and arm > leg) with aphasia in dominant hemisphere.",
        relatedCondition: "Acute Ischaemic Stroke within 4.5-hour thrombolysis window",
        recommendedTutorQuery: "Explain inclusion and exclusion criteria for IV Alteplase in acute ischaemic stroke per NICE NG128.",
        highYieldMcqId: "mcq_stroke_01",
        niceGuidelineRef: "NICE-NG128:Section 1.4",
      },
      {
        id: "circle_of_willis",
        name: "Anterior Communicating Artery (ACom)",
        position: [0.0, 0.2, 0.8],
        clinicalSignificance: "Most common site of saccular (berry) aneurysms. Rupture produces thunderclap headache and xanthochromia.",
        relatedCondition: "Subarachnoid Haemorrhage (SAH)",
        recommendedTutorQuery: "What is the diagnostic algorithm for suspected SAH when CT head is negative after 6 hours?",
        highYieldMcqId: "mcq_sah_01",
        niceGuidelineRef: "NICE-NG228:Section 1.1",
      },
    ],
  },
  {
    id: "pulmonary",
    name: "Respiratory System",
    description: "Tracheobronchial tree, alveolar gas exchange surfaces, and pulmonary vasculature.",
    clinicalFocus: "Pulmonary Embolism, Tension Pneumothorax, Acute Severe Asthma",
    hotspots: [
      {
        id: "pulmonary_trunk",
        name: "Main Pulmonary Trunk Bifurcation",
        position: [0.0, 0.8, -0.2],
        clinicalSignificance: "Saddle embolus obstructs right ventricular outflow, leading to acute cor pulmonale, hemodynamic collapse, and S1Q3T3 on ECG.",
        relatedCondition: "Massive High-Risk Pulmonary Embolism with Hypotension",
        recommendedTutorQuery: "Review immediate systemic thrombolysis dosing and contraindications in high-risk PE.",
        highYieldMcqId: "mcq_pe_01",
        niceGuidelineRef: "NICE-NG158:Section 1.3",
      },
    ],
  },
];

export const PLAB_QUESTIONS: PLABQuestion[] = [
  {
    id: "mcq_stemi_01",
    topic: "Cardiology",
    specialty: "Acute Coronary Syndromes",
    vignette:
      "A 56-year-old male with a history of hypertension and type 2 diabetes presents to the Emergency Department with severe crushing central chest pain radiating to his left shoulder of 45 minutes duration. He is diaphoretic and pale. BP is 135/85 mmHg, HR is 92 bpm, and oxygen saturation is 98% on room air. 12-lead ECG reveals 3mm ST-segment elevation in leads V1 to V4 with reciprocal ST depression in III and aVF. The nearest PCI center is located 25 minutes away. What is the most appropriate definitive management strategy?",
    options: [
      {
        key: "A",
        text: "Immediate intravenous thrombolysis with Tenecteplase",
        isCorrect: false,
        eliminationRationale: "Thrombolysis is only recommended if PPCI cannot be delivered within 120 minutes of ECG diagnosis.",
      },
      {
        key: "B",
        text: "Transfer immediately for Primary Percutaneous Coronary Intervention (PPCI)",
        isCorrect: true,
        eliminationRationale: "PPCI is the gold-standard reperfusion strategy when it can be delivered within 120 minutes of diagnosis (travel time is only 25 mins).",
      },
      {
        key: "C",
        text: "Urgent CT Pulmonary Angiogram to rule out pulmonary embolism",
        isCorrect: false,
        eliminationRationale: "Clear STEMI on ECG with classical symptoms requires immediate reperfusion without delaying for aortic or pulmonary imaging unless dissection is suspected.",
      },
      {
        key: "D",
        text: "Oral Aspirin 300mg and discharge with urgent cardiology outpatient clinic follow-up",
        isCorrect: false,
        eliminationRationale: "Acute STEMI is an emergency with high immediate mortality; discharge is contraindicated.",
      },
      {
        key: "E",
        text: "Intravenous unfractionated heparin bolus as sole reperfusion therapy",
        isCorrect: false,
        eliminationRationale: "Heparin provides adjunctive anticoagulation but does not mechanically or enzymatically reperfuse the occluded LAD artery.",
      },
    ],
    explanation:
      "According to NICE Guideline NG185 (Section 1.2), Primary Percutaneous Coronary Intervention (PPCI) is the preferred reperfusion strategy for patients presenting with STEMI within 12 hours of symptom onset if PPCI can be performed within 120 minutes of when fibrinolysis could have been given. Here the PCI center is 25 minutes away, making PPCI the mandatory first-line approach alongside dual antiplatelet therapy (Aspirin 300mg + Prasugrel/Ticagrelor) and unfractionated heparin.",
    evidenceRef: "[NICE-NG185:Reperfusion-STEMI-B0012]",
    difficulty: "Competent",
  },
  {
    id: "mcq_dissection_01",
    topic: "Cardiology",
    specialty: "Vascular Emergencies",
    vignette:
      "A 62-year-old male presents with sudden-onset, severe, 'tearing' chest pain radiating through to his back between the scapulae. On examination, blood pressure in the right arm is 184/102 mmHg, while in the left arm it is 128/78 mmHg. A new early diastolic murmur is audible at the right sternal edge. Neurological exam reveals mild left-sided weakness. What is the single most definitive diagnostic investigation?",
    options: [
      {
        key: "A",
        text: "CT Angiography of the Chest, Abdomen, and Pelvis",
        isCorrect: true,
        eliminationRationale: "CT Aortography is the first-line imaging modality of choice for hemodynamically stable patients with suspected acute aortic dissection.",
      },
      {
        key: "B",
        text: "Transthoracic Echocardiogram (TTE)",
        isCorrect: false,
        eliminationRationale: "TTE has low sensitivity for ascending and descending aortic dissection compared to CTA or Transesophageal Echocardiography (TOE).",
      },
      {
        key: "C",
        text: "Lumbar Puncture to evaluate neurological signs",
        isCorrect: false,
        eliminationRationale: "Neurological deficits here stem from innominate or carotid artery dissection; LP is contraindicated and wastes time.",
      },
      {
        key: "D",
        text: "Intravenous Thrombolysis for presumptive brainstem ischemia",
        isCorrect: false,
        eliminationRationale: "Thrombolysis in acute aortic dissection is catastrophic and fatal due to torrential pericardial tamponade or exsanguination.",
      },
      {
        key: "E",
        text: "Exercise ECG stress testing",
        isCorrect: false,
        eliminationRationale: "Stress testing in suspected acute dissection causes immediate aortic rupture.",
      },
    ],
    explanation:
      "Per NICE Guidelines and European Society of Cardiology recommendations, contrast-enhanced CT Angiography (triple-rule-out or full aortogram) is the gold standard imaging modality for suspected aortic dissection. Pulse differential between arms (>20 mmHg difference) combined with new aortic regurgitation strongly points toward a Stanford Type A dissection requiring urgent cardiothoracic surgical consultation.",
    evidenceRef: "[NICE-CG95:ChestPain-AorticDissection-B0044]",
    difficulty: "Mastery",
  },
];

export const DEMO_PATIENT_CASE: PatientCase = {
  id: "case_tamponade_01",
  title: "Acute Hemodynamic Collapse in Emergency Resuscitation",
  patient: {
    name: "Arthur Pendelton",
    age: 58,
    gender: "Male",
    occupation: "Civil Engineer",
    presentingComplaint: "Sudden onset chest tightness, marked dyspnea, and dizziness",
    onset: "2 hours ago while gardening; acute deterioration upon arrival",
    pastHistory: [
      "Metastatic Non-Small Cell Lung Cancer (adenocarcinoma)",
      "Systemic Hypertension on Ramipril",
      "History of transient ischemic attack 3 years ago",
    ],
    allergies: ["Penicillin (severe urticaria and bronchospasm)"],
    medications: ["Ramipril 5mg OD", "Carboplatin/Pemetrexed cycle completed 10 days ago"],
  },
  vitals: {
    heartRate: 122,
    bloodPressure: "86/60",
    oxygenSat: 91,
    respiratoryRate: 28,
    temperature: 36.8,
    ecgRhythm: "Sinus Tachycardia",
  },
  symptomsTimeline: [
    { time: "14:00", event: "Onset of retrosternal heaviness and breathlessness at home.", severity: "moderate" },
    { time: "15:15", event: "Ambulance transit; oxygen administered at 4L/min via Hudson mask.", severity: "moderate" },
    { time: "15:45", event: "Arrival at Resuscitation Bay. Markedly distended jugular veins observed to the angle of the jaw.", severity: "critical" },
    { time: "15:50", event: "Muffled heart sounds on auscultation. Systolic BP drops by 16 mmHg during normal inspiration (Pulsus Paradoxus).", severity: "critical" },
  ],
  criticalContraindications: [
    "Do NOT administer high-dose vasodilators (e.g. GTN, Hydralazine) - will precipitate fatal circulatory arrest by reducing preload.",
    "Do NOT administer Thrombolysis (Tenecteplase/Alteplase) - pericardial hemorrhagic tamponade.",
    "Do NOT perform aggressive positive pressure mechanical ventilation prior to relieving tamponade if avoidable.",
  ],
  availableInterventions: [
    {
      id: "action_echo",
      name: "Immediate Bedside Focused Cardiac Ultrasound (POCUS / Echo)",
      type: "investigation",
      isOptimal: true,
      aiFeedback: "EXCELLENT. POCUS reveals large circumferential pericardial effusion with diastolic collapse of the right ventricle and IVC plethora. Confirms cardiac tamponade (Beck's triad).",
    },
    {
      id: "action_fluids",
      name: "Intravenous 0.9% Normal Saline Bolus (500ml)",
      type: "medication",
      isOptimal: true,
      aiFeedback: "CORRECT TEMPORIZING MEASURE. Volume expansion increases right ventricular end-diastolic pressure, temporarily resisting pericardial compressive forces while preparing for pericardiocentesis.",
    },
    {
      id: "action_pericardiocentesis",
      name: "Emergency Ultrasound-Guided Pericardiocentesis",
      type: "procedure",
      isOptimal: true,
      aiFeedback: "LIFE-SAVING DEFINITIVE INTERVENTION. Aspiration of 120ml of blood-tinged fluid immediately restores cardiac output, elevating BP from 86/60 to 118/74 mmHg and dropping HR to 88 bpm.",
    },
    {
      id: "action_gtn",
      name: "Sublingual Glyceryl Trinitrate (GTN) 400mcg",
      type: "medication",
      isContraindicated: true,
      contraindicationReason: "CRITICAL SAFETY VIOLATION: Nitrates cause acute venodilation and reduce cardiac preload. In cardiac tamponade, filling depends entirely on elevated venous pressure. Preload reduction triggers immediate asystolic arrest.",
      aiFeedback: "SAFETY FILTER TRIGGERED: Vasodilators strictly contraindicated. Preload is vital for maintaining minimum cardiac output against high intrapericardial pressures.",
    },
    {
      id: "action_thrombolysis",
      name: "Intravenous Alteplase Bolus",
      type: "medication",
      isContraindicated: true,
      contraindicationReason: "CATASTROPHIC HAZARD: Thrombolysis in malignant or hemorrhagic pericarditis converts effusion into rapid fatal hemopericardium.",
      aiFeedback: "SAFETY FILTER TRIGGERED: Fibrinolysis rejected by Stage-D Clinical Safety Validator.",
    },
  ],
};

export const INITIAL_STUDENT_PROFILE: StudentMasteryProfile = {
  studentId: "user_alice",
  studentName: "Dr. Alice Vance",
  overallAccuracy: 0.74,
  masteryLevel: "COMPETENT",
  totalAttempts: 34,
  specialtyMastery: [
    { specialty: "Cardiology", accuracy: 0.68, status: "neutral" },
    { specialty: "Respiratory", accuracy: 0.86, status: "strong" },
    { specialty: "Neurology", accuracy: 0.72, status: "neutral" },
    { specialty: "Emergency & Resuscitation", accuracy: 0.61, status: "weak" },
    { specialty: "Pharmacology & Toxicology", accuracy: 0.58, status: "weak" },
  ],
  weakTopics: ["Cardiac Tamponade vs Constriction", "Inotropic vs Vasodilator Selection", "Secondary Prevention in Post-CABG"],
  activeRecommendations: [
    {
      id: "rec_01",
      title: "Master Beck's Triad in Acute Tamponade",
      reason: "Recent attempt identified difficulty distinguishing tamponade from acute tension pneumothorax.",
      priority: "HIGH",
      actionType: "simulation",
    },
    {
      id: "rec_02",
      title: "3D Coronary Anatomy & Anterior STEMI",
      reason: "Correlate LAD occlusion with anterior V1-V4 lead distribution.",
      priority: "MEDIUM",
      actionType: "anatomy",
    },
    {
      id: "rec_03",
      title: "Antiplatelet Protocols in ACS",
      reason: "NICE NG185 dual antiplatelet therapy questions frequently missed.",
      priority: "MEDIUM",
      actionType: "quiz",
    },
  ],
};

export const PIPELINE_STAGES: PipelineStageInfo[] = [
  {
    id: "stage_r",
    name: "Stage-R",
    code: "Advanced Retrieval",
    purpose: "Hybrid sparse/dense retrieval with cross-encoder reranking & extractive context compression.",
    status: "FROZEN_SECURE",
    latencyMs: 38,
    inputContract: "ClinicalQueryContext",
    outputContract: "EvidencePacket",
  },
  {
    id: "stage_b",
    name: "Stage-B",
    code: "Evidence Verification",
    purpose: "Strict claim verification, citation integrity checks, and evidence policy grounding.",
    status: "FROZEN_SECURE",
    latencyMs: 44,
    inputContract: "VerifiedClaimRequest",
    outputContract: "GroundingVerificationResult",
  },
  {
    id: "stage_c",
    name: "Stage-C",
    code: "Question Generation",
    purpose: "Evidence-grounded PLAB Single Best Answer generation with distractor plausibility validation.",
    status: "FROZEN_SECURE",
    latencyMs: 72,
    inputContract: "ClinicalVignetteSpec",
    outputContract: "ValidatedMCQRecord",
  },
  {
    id: "stage_d",
    name: "Stage-D",
    code: "Medical Tutor",
    purpose: "Socratic explanation modes with active clinical safety validator preventing hallucinated dosages.",
    status: "FROZEN_SECURE",
    latencyMs: 65,
    inputContract: "TutorInteractionPrompt",
    outputContract: "ClinicalTutorResponse",
  },
  {
    id: "stage_e",
    name: "Stage-E",
    code: "Adaptive Intelligence",
    purpose: "Deterministic student mastery scoring, weakness detection, and explainable recommendations.",
    status: "FROZEN_SECURE",
    latencyMs: 12,
    inputContract: "AttemptHistoryStream",
    outputContract: "StudentMasteryProfile",
  },
  {
    id: "stage_f",
    name: "Stage-F",
    code: "Intelligence Orchestration",
    purpose: "Unified routing, adaptive difficulty engine, and clinical case simulation state management.",
    status: "FROZEN_SECURE",
    latencyMs: 51,
    inputContract: "PlatformUserGoal",
    outputContract: "OrchestratedPlatformResponse",
  },
  {
    id: "stage_g",
    name: "Stage-G",
    code: "Product & Deployment",
    purpose: "Multi-tenancy isolation, AI gateway rate quotas, PostgreSQL-ready repositories, and compliance audit.",
    status: "FROZEN_SECURE",
    latencyMs: 8,
    inputContract: "APIRequestEnvelope",
    outputContract: "APIResponseEnvelope",
  },
];
